spring.application.name=betgame

#  spring.datasource.url=jdbc:postgresql://kp-dev.de:6432/betgame_db
spring.datasource.url=jdbc:postgresql://localhost:6432/betgame_db
spring.datasource.username=kpdev
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
logging.level.org.springframework.boot.autoconfigure=ERROR

server.error.include-message=always
server.error.include-stacktrace=always
server.error.include-binding-errors=always

server.port=8060

jwt.key: yQq9ZwDGRXCuCjuuSNAqB11cx3dcD+mizAMvjSQDrQbnEfcviTwYFhuKXTArg2Y4JfZYVldyydJYNIxZu4kXct20rC80M9+RVMM+CdNSLfOBudSBRMhwiJg9+RG2L2iGnlu7c34lcdgKJZYFMtWGbcVGYw8CNWi80HbiPxdw36i2
jwt.access-token-expiration: 3600000
jwt.refresh-token-expiration: 86400000

football.api.url=https://api.football-data.org
football.api.key=7532258034124598936fb4af79c2f683
